module LocationsHelper
  def auckland_suburbs
    ["Arch Hill",
    "Auckland CBD",
    "Avondale",
    "Balmoral",
    "Blockhouse Bay",
    "Eden Terrace",
    "Eden Valley",
    "Ellerslie",
    "Epsom",
    "Freemans Bay",
    "Glendowie",
    "Glen Innes",
    "Grafton",
    "Greenlane",
    "Greenwoods Corner",
    "Grey Lynn",
    "Herne Bay",
    "Hillsborough",
    "Kingsland",
    "Kohimarama",
    "Lynfield",
    "Meadowbank",
    "Mission Bay",
    "Morningside",
    "Mount Albert",
    "Mount Eden",
    "Mount Roskill",
    "Mount Wellington",
    "Newmarket",
    "Newton",
    "New Windsor",
    "Onehunga",
    "One Tree Hill",
    "Orakei",
    "Oranga",
    "Otahuhu",
    "Owairaka",
    "Panmure",
    "Parnell",
    "Penrose",
    "Point England",
    "Point Chevalier",
    "Ponsonby",
    "Remuera",
    "Royal Oak",
    "Saint Heliers",
    "Saint Johns",
    "Saint Marys Bay",
    "Sandringham",
    "Stonefields",
    "Tamaki",
    "Te Papapa",
    "Three Kings",
    "Waikowhai",
    "Wai o Taiki Bay",
    "Waterview",
    "Western Springs",
    "Westfield",
    "Westmere"]
  end

  def nz_cities
    ["Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier-Hastings",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "Whangarei",
    "New Plymouth",
    "Invercargill",
    "Whanganui",
    "Gisborne"]
  end


end
